version: '3.9'
services:
  trainer:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    image: yins/loader-benchmark:${TAG:-latest}
    volumes:
      - ./datasets:/home/worker/workspace/datasets
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  s3:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - ./s3-data:/data
